### PR TITLE
Prefer [] as delimiters for `%` array literals

### PR DESCRIPTION
**Pull request by rgabo**

### CODE REVIEW

**Comment by rgabo** [comment]
@tmichel @martonpe turns out there's already a PR for `%w(` vs `%w[` :smile:

Let's discuss here.

**Comment by tmichel** [comment]
I'm all for it. I usually use the `%w[...]` for anyway. Let's merge this!

**Comment by rgabo** [comment]
There's been quite a few changes upstream, let's merge upstream before merging this PR.

**Comment by rgabo** [comment]
@tmichel awesome! Next time upstream should be merged using a pull request (if possible) so that we can look at the diff and decide whether we agree with it.

**Pull request merged**
